HipDronesProject/Controllers/CustomerController.cs
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using HipDronesProject.Data;
using HipDronesProject.Data.Models;
using HipDronesProject.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;


namespace HipDronesProject.Controllers
{
    public class CustomerController : Controller
    {
        private ICustomerService _customerData;

        public CustomerController(ICustomerService customerData)
        {
            _customerData = customerData;

        }

        public IActionResult Index()
        {
            return View(_customerData.GetAll());
        }

        public IActionResult Details(int id)
        {
            var model = _customerData.Get(id);
            if (model == null)
            {
                return RedirectToAction("Index", "Home");
            }

            return View(model);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Customer customer)
        {
            if (ModelState.IsValid)
            {
                var tmp = new Customer
                {
                    FirstName = customer.FirstName,
                    LastName = customer.LastName,
                    Email = customer.Email
                    };

                tmp = _customerData.Add(tmp);

                return RedirectToAction(nameof(Index), new { id = tmp.Id });
            }
            return View();
        }

        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = _customerData.GetAll().FirstOrDefault(m => m.Id == id);
            if (customer == null)
            {
                return NotFound();
            }
            return View(customer);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Customer customer)
        {
            if (customer == null)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                _customerData.Update(customer);
                return RedirectToAction(nameof(Index));
            }

            return View(customer);
        }


        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = _customerData.GetAll().FirstOrDefault(m => m.Id == id);

            if (customer == null)
            {
                return NotFound();
            }

            return View();
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {

            _customerData.Delete(id);
            return RedirectToAction(nameof(Index));

        }
    }


}

HipDronesProject/Controllers/DroneController.cs
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using HipDronesProject.Data;
using HipDronesProject.Data.Models;
using HipDronesProject.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;


namespace HipDronesProject.Controllers
{
    public class DroneController : Controller
    {
        private IDroneService _droneData;

        public DroneController(IDroneService droneData)
        {
            _droneData = droneData;

        }

        public IActionResult Index()
        {
            return View(_droneData.GetAll());
        }

        public IActionResult Details(int id)
        {
            var model = _droneData.Get(id);
            if (model == null)
            {
                return RedirectToAction("Index", "Home");
            }

            return View(model);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Drone drone)
        {
            if (ModelState.IsValid)
            {
                var tmpDrone = new Drone
                {
                    Name = drone.Name,
                    RegId = drone.RegId,
                    Category = drone.Category,
                    Info = drone.Info,
                    Available = drone.Available
                };

                tmpDrone = _droneData.Add(tmpDrone);

                return RedirectToAction(nameof(Index), new { id = tmpDrone.Id });
            }
            return View();
        }

        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var drone = _droneData.GetAll().FirstOrDefault(m => m.Id == id);
            if (drone == null)
            {
                return NotFound();
            }
            return View(drone);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Drone drone)
        {
            if (drone == null)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                _droneData.Update(drone);
                return RedirectToAction(nameof(Index));
            }

            return View(drone);
        }


        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var drone = _droneData.GetAll().FirstOrDefault(m => m.Id == id);

            if (drone == null)
            {
                return NotFound();
            }

            return View();
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {

            _droneData.Delete(id);
            return RedirectToAction(nameof(Index));

        }
    }


}

HipDronesProject/Controllers/FilesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using HipDronesProject.Data.Models;
using HipDronesProject.Interfaces;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.Metadata.Profiles.Exif;

namespace HipDronesProject.Controllers
{
    public class FilesController : Controller
    {
        private readonly IWebHostEnvironment _env;
        private readonly IPictureService _pictureService;

        public FilesController(IWebHostEnvironment env, IPictureService pictureService)
        {
            _pictureService = pictureService;
            _env = env;
        }

        public IActionResult Media()
        {
            return View();
        }

        public IActionResult PictureIndex()
        {
            return View();
        }

        public IActionResult Gallery()
        {

            
            return View();
        }

        [HttpGet]
        public IActionResult UploadPicture()
        {
            return View();
        }

        
        [HttpPost]
        public async Task<IActionResult> UploadPicture(Picture model)
        {
            if (model.ImageFile.Length > 0)
            {
                string path = Path.Combine(_env.WebRootPath, "images/uploaded");
                using (var fs = new FileStream(Path.Combine(path, model.ImageFile.FileName), FileMode.Create))
                {
                    await model.ImageFile.CopyToAsync(fs);
                }

               

            }

            return Ok(model);
        }


        [HttpGet]
        public async Task<IActionResult> Details(Picture model)
        {
            var file = model.ImageFile;

            string path = Path.Combine(_env.WebRootPath, "images/uploaded");
            using (var fs = new FileStream(Path.Combine(path, file.FileName), FileMode.Create))
            {
                await file.CopyToAsync(fs);
            }

            using (var img = Image.Load(Path.Combine(path, file.FileName)))
            {
                model.Source = $"/images/uploaded/{file.FileName}";
                model.Path = Path.GetExtension(file.FileName).Substring(1);
                model.Width = img.Width;
                model.Height = img.Height;
                model.Size = file.Length / 1000;
                if (model.Latitude != null)
                    model.Latitude =
                        img.Metadata.ExifProfile.GetValue(ExifTag.GPSLatitude).ToString();
                if (model.Longitude != null)
                    model.Longitude =
                        img.Metadata.ExifProfile.GetValue(ExifTag.GPSLongitude).ToString();
                if (model.Altitude != null)
                    model.Altitude =
                        img.Metadata.ExifProfile.GetValue(ExifTag.GPSAltitude).ToString();

                return Ok(model);

            }
        }
    }
}

HipDronesProject/Controllers/PilotController.cs
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using HipDronesProject.Data;
using HipDronesProject.Data.Models;
using HipDronesProject.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;


namespace HipDronesProject.Controllers
{
    public class PilotController : Controller
    {
        private IPilotService _pilotData;

        public PilotController(IPilotService pilotData)
        {
            _pilotData = pilotData;

        }

        public IActionResult Index()
        {
            return View(_pilotData.GetAll());
        }

        public IActionResult Details(int id)
        {
            var model = _pilotData.Get(id);
            if (model == null)
            {
                return RedirectToAction("Index", "Home");
            }

            return View(model);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Pilot pilot)
        {
            if (ModelState.IsValid)
            {
                var tmp = new Pilot
                {
                    Name = pilot.Name,
                    Info = pilot.Info,
                    Available = pilot.Available

                };

                tmp = _pilotData.Add(tmp);

                return RedirectToAction(nameof(Index), new { id = tmp.Id });
            }
            return View();
        }

        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var obj = _pilotData.GetAll().FirstOrDefault(m => m.Id == id);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Pilot obj)
        {
            if (obj == null)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                _pilotData.Update(obj);
                return RedirectToAction(nameof(Index));
            }

            return View(obj);
        }


        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var obj = _pilotData.GetAll().FirstOrDefault(m => m.Id == id);

            if (obj == null)
            {
                return NotFound();
            }

            return View();
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {

            _pilotData.Delete(id);
            return RedirectToAction(nameof(Index));

        }
    }


}

HipDronesProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Hip Drones</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <a>
                    <img src="~/images/TLogo.png" alt="Company logo" height="50" />
                </a>

                <a asp-controller="Home" asp-action="Index" class="navbar-brand"></a>

            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Account" asp-action="LoggedIn">Home</a></li>
                    <li><a asp-area="" asp-controller="Drone" asp-action="Index">Drones</a></li>
                    <li><a asp-area="" asp-controller="Customer" asp-action="Index">Customers</a></li>
                    <li><a asp-area="" asp-controller="Pilot" asp-action="Index">Pilots</a></li>
                    <li><a asp-area="" asp-controller="Assignment" asp-action="Index">Assignments</a></li>
                    <li><a asp-area="" asp-controller="Files" asp-action="Media">Media</a></li>
                    <li><a asp-area="" asp-controller="Files" asp-action="UploadPicture">Upload File</a></li>


                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner">
            <div class="item active">
                <center> <img src="images\dronepictures\DJI_Inspire2_2.jpg" style="width:75%"></center>
            </div>
            <div class="item">
                <center> <img src="images\dronepictures\DJI_Spark_1.jpg" style="width:75%"></center>
            </div>
            <div class="item">
                <center> <img src="images\dronepictures\DJI_Spark_2.jpg" style="width:75%"></center>
            </div>
        </div>

        <!-- Left and right controls -->
        <a class="left carousel-control" href="#myCarousel" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Hip Drones</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>